import { describe, it, expect } from 'vitest';
import { findStartApp } from '../src/main/windowsApi/appDiscovery';
import type { StartMenuApp } from '../src/main/windowsApi/appDiscovery';

describe('findStartApp', () => {
  const apps: StartMenuApp[] = [
    { name: 'WhatsApp', appId: '5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App' },
    { name: 'Visual Studio Code', appId: 'Microsoft.VisualStudioCode' },
    { name: 'Notepad', appId: '{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\notepad.exe' },
    { name: 'Calculator', appId: 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App' },
    { name: 'Uninstall Node.js', appId: 'Microsoft.AutoGenerated.{guid}' },
    { name: 'Node.js website', appId: 'https://nodejs.org/' },
  ];

  it('matches an exact (normalized) name', () => {
    expect(findStartApp('WhatsApp', apps)?.appId).toBe('5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App');
    expect(findStartApp('whats app', apps)?.appId).toBe('5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App');
  });

  it('understands common short/alternate names via the alias table', () => {
    expect(findStartApp('vscode', apps)?.name).toBe('Visual Studio Code');
    expect(findStartApp('vs code', apps)?.name).toBe('Visual Studio Code');
  });

  it('never matches an uninstaller or a website shortcut, even by direct substring', () => {
    expect(findStartApp('node', apps)).toBeNull();
  });

  it('returns null rather than a wild guess for a very short or empty query', () => {
    expect(findStartApp('', apps)).toBeNull();
    expect(findStartApp('a', apps)).toBeNull();
  });

  it('returns null when nothing plausible matches', () => {
    expect(findStartApp('photoshop', apps)).toBeNull();
  });

  it('prefers the shortest matching name when several contain the query', () => {
    const ambiguous: StartMenuApp[] = [
      { name: 'Notepad', appId: 'a' },
      { name: 'Notepad++', appId: 'b' },
    ];
    expect(findStartApp('notepad', ambiguous)?.name).toBe('Notepad');
  });
});
